name: nix

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --all-systems --no-build
      - run: nix build .#scala-pds
